name: Build mpv-android (arm64 signed release)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # 2️⃣ Setup JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3️⃣ Install dependencies for building native libs
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake meson ninja-build yasm nasm gettext python3 git unzip

      # 4️⃣ Setup Android NDK
      - name: Set up Android NDK (r26d)
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d

      # 5️⃣ Give execute permissions for build scripts
      - name: Give execute permissions
        run: chmod +x buildscripts/*.sh buildscripts/include/*.sh buildscripts/scripts/*.sh

      # 6️⃣ Download SDK & dependencies
      - name: Download SDK & dependencies
        run: |
          cd buildscripts
          ./download.sh
          cd ..

      # 7️⃣ Build native libraries (ARM64)
      - name: Build native libraries
        run: |
          cd buildscripts
          ./buildall.sh --arch arm64
          cd ..

      # 8️⃣ Copy native libraries to jniLibs
      - name: Copy native libraries
        run: |
          mkdir -p app/src/main/jniLibs/arm64-v8a
          cp -v buildscripts/prefix/arm64/usr/local/lib/*.so app/src/main/jniLibs/arm64-v8a/ || true

      # 9️⃣ Build unsigned release APK
      - name: Build unsigned release APK
        run: |
          set -x
          ./gradlew assembleRelease | tee build_error_log.txt

      # 🔟 Locate the unsigned APK
      - name: Locate unsigned APK
        id: locate_apk
        run: |
          APK_PATH=$(find app/build/outputs/apk/ -name "*arm64-v8a-release-unsigned.apk" | head -n 1)
          echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT
          echo "Found APK: $APK_PATH"

      # 1️⃣1️⃣ Create a test keystore
      - name: Create test keystore
        run: |
          keytool -genkeypair \
            -v \
            -keystore test-release-key.jks \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -alias mpvkey \
            -storepass android \
            -keypass android \
            -dname "CN=mpv, OU=Dev, O=mpv, L=Internet, ST=World, C=US"

      # 1️⃣2️⃣ Find apksigner
      - name: Find apksigner path
        id: apksigner
        run: |
          APK_SIGNER_PATH=$(find $ANDROID_HOME/build-tools -name apksigner | sort | tail -n 1)
          echo "apksigner_path=$APK_SIGNER_PATH" >> $GITHUB_OUTPUT
          echo "Found apksigner at: $APK_SIGNER_PATH"

      # 1️⃣3️⃣ Sign the APK
      - name: Sign APK
        run: |
          "${{ steps.apksigner.outputs.apksigner_path }}" sign \
            --ks test-release-key.jks \
            --ks-pass pass:android \
            --key-pass pass:android \
            --ks-key-alias mpvkey \
            --out signed-release.apk \
            "${{ steps.locate_apk.outputs.apk_path }}"

      # 1️⃣4️⃣ Verify signed APK
      - name: Verify signed APK
        run: |
          "${{ steps.apksigner.outputs.apksigner_path }}" verify --verbose --print-certs signed-release.apk

      # 1️⃣5️⃣ Upload signed APK
      - name: Upload signed ARM64 release
        uses: actions/upload-artifact@v4
        with:
          name: mpv-android-arm64-release-signed-${{ github.run_number }}
          path: signed-release.apk

      # 1️⃣6️⃣ Upload build logs
      - name: Upload build logs
        uses: actions/upload-artifact@v4
        with:
          name: build_error_log
          path: build_error_log.txt
